version: "3.8"
name: cursos-nestjs
services:
  # --------------------
  # Infraestructura
  # --------------------

  # Servicio de mensajería NATS
  nats-server:
    image: nats:latest

  # --------------------
  # Microservicios
  # --------------------

  # API Gateway principal
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
    depends_on:
      - nats-server

  # Microservicio de productos
  products-service:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-service
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    depends_on:
      - nats-server

  # Microservicio de órdenes
  orders-service:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    image: orders-service
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DB_URL}
    depends_on:
      - nats-server
    # command: sh -c "npx prisma migrate deploy && node dist/main.js"

  # Microservicio de pagos
  payments-service:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-service
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    depends_on:
      - nats-server
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}

  # Microservicio de Autentificacion
  auth-service:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - nats-server
## Servicio de Hookdeck para webhooks
#hookdeck:
#  image: hookdeck/hookdeck-cli:latest
#  entrypoint: ["/bin/sh"]
#  command: -c "hookdeck ci --api-key ${HOOCKED_TOKEN} && hookdeck listen http://payments-service:3003 ${HOOCKED_SOURCE}"
#  depends_on:
#    - client-gateway
#    - products-service
#    - orders-service
#    - payments-service
#  environment:
#    - HOOKDECK_API_KEY=${HOOCKED_TOKEN} # Usa tu token real
#    - HOOKDECK_CONFIG_DIR=/data
#  volumes:
#    - ./hookdeck-data:/data
#
